kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0101
  annotations:
    volume.alpha.kubernetes.io/storage-class: standard
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data101"
